# superset:
#   url: https://bidarshan-dev.dcservices.in/
#   username: GC-TTS
#   password: 250671
  
# superset:
#   url: https://bidarshan-dev.dcservices.in/
#   username: GC-TTS
#   password: 250671
#   first_name: devender
#   last-name: singh
#   email: devendersingh@cdac.in

superset:
 url: https://bidarshan.dcservices.in/
 username: Embed-CGHS
 password: embed
 first_name: Guest
 last-name: user
 email: guest@gmail.com
  
server:
  port: 8088
  address: 10.226.25.31 # Replace with a valid IP


spring:
 autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


