server:
  port: 8084
  # address: 10.226.25.31

spring:
  application:
    name: git-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/git_service_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  
  security:
    filter:
      order: 10
  
  boot:
    admin:
      client:
        url: http://localhost:9090 # Admin server URL

# JWT configuration for git service
jwt:
  secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}

logging:
  level:
    org.springframework.web: INFO
    com.git: DEBUG

# Eureka configuration (uncomment if using service discovery)
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://ttsdashboard.com:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
