# superset:
#  url: http://10.226.30.23:8088
#  username: guest-guest
#  password: 12345
#  first_name: Guest
#  last-name: user
#  email: guest@gmail.com


 superset:
  url: https://bidarshan-dev.dcservices.in/
  username: guest
  password: guest
  first_name: devender
  last-name: singh
  email: devendersingh@cdac.in

server:
  port: 8089
  address: 10.226.25.31 # Replace with a valid IP


spring:
 autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

